version: '2'
services:

  ttg-nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${TTG_SSL}:/ssl"
    links:
      - ttg-web-backend
      - ttg-web-frontend
      - ttg-saved-schedules

  ttg-web-backend:
    image: docker.timetablegenerator.io/ttg/ttg-web-backend
    environment:
      - "SECRET_KEY=${TTG_WEB_BACKEND_SECRET}"
    expose:
      - "80"

  ttg-web-frontend:
    image: docker.timetablegenerator.io/ttg/ttg-web-frontend
    expose:
      - "80"

  ttg-saved-schedules:
    image: docker.timetablegenerator.io/ttg/ttg-saved-schedules
    links:
      - ttg-mongodb

  ttg-mongodb:
    image: mongo:3
    volumes:
      - "${TTG_MONGO_VOL}:/data/db"
