version: '2'
services:

  ttg-nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    links:
      - ttg-web-backend
      - ttg-web-frontend
      - ttg-saved-schedules

  ttg-web-backend:
    image: docker.timetablegenerator.com/ttg/ttg-web-backend
    expose:
      - "80"

  ttg-web-frontend:
    image: docker.timetablegenerator.com/ttg/ttg-web-frontend
    expose:
      - "80"

  ttg-saved-schedules:
    image: docker.timetablegenerator.com/ttg/ttg-saved-schedules
    links:
      - ttg-mongodb

  ttg-mongodb:
    image: mongo:3
    volume:
      - "${TTG_MONGO_VOL}":/data/db
